name: Release

on:
  push


jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: get version from tag
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        echo $env:GITHUB_REF
        $env:GITHUB_REF -match "refs/tags/(?<content>.*)"
        $RELEASE_VERSION = $matches["content"]
        echo "::set-env name=RELEASE_VERSION::$RELEASE_VERSION" 
        $env:GITHUB_REF -match "refs/tags/v(?<content>.*)"
        $NUMERICAL_VERSION = $matches["content"]
        echo "::set-env name=NUMERICAL_VERSION::$NUMERICAL_VERSION"
        $FULL_VERSION = "$NUMERICAL_VERSION.$env:GITHUB_RUN_NUMBER"
        echo "::set-env name=FULL_VERSION::$FULL_VERSION"
        echo "Release version = $RELEASE_VERSION"
        echo "Numerical version = $NUMERICAL_VERSION"
        echo "Full version = $FULL_VERSION"
